server:
    port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 15
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      encoding: utf-8
mybatis:
  configuration:
   map-underscore-to-camel-case: true